---
- hosts: nuc
  gather_facts: yes
  become: yes

  roles:
    - role: system
      tags:
        - system

- hosts: nuc
  gather_facts: yes
  become: yes
  become_user: "{{ username }}"
  roles:
  - dev
  - dotfiles