---
#
# Tasks and roles for all hosts
#

- hosts: all
  gather_facts: no
  become: yes

  roles:
    #
    # Basics
    #
    - role: system
      tags: 
        - system

- hosts: nuc
  become: yes
  become_user: "{{ username }}"
  roles:
  #
  # Dotfiles for the main server
  #
  - role: dotfiles