---
- hosts: all
  gather_facts: yes
  become: yes

  roles:
    - role: system
      tags:
        - system

- hosts: nuc
  become: yes
  become_user: "{{ username }}"
  roles:
  #
  # Dotfiles for the main server
  #
  - dotfiles