---
- name: Make sure the necessary pip packages are installed
  pip:
    name: 
      - bcrypt
      - cryptography>=3.0
    state: present

- name: Check for any existing keys
  stat:
    path: ~/.ssh/github_rsa
  register: git_ssh_key

- name: Generate a new ssh key (if one doesnt exist)
  community.crypto.openssh_keypair:
    path: ~/.ssh/github_rsa
    passphrase: "{{ github_rsa_passphrase }}"
  when: not git_ssh_key.stat.exists

# - name: Grab the pub key
#   shell: cat "/home/{{username}}/.ssh/github_rsa.pub"
#   register: github_pub_key

# - name: Print the pub key
#   debug:
#     msg: "{{ github_pub_key.stdout }}"