---

- name: Install Kubernetes
  snap:
    name: microk8s
    classic: true
    state: present

- name: Add user to microk8s admin group
  user:
    name: "{{ username }}"
    groups:
      - microk8s
    append: yes

- name: Change group ownership of ~/.kube
  file:
    path: "/home/{{ username }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Grab the value of microk8s status
  shell: "microk8s status"
  register: microk_status

- name: Output microk8s status
  debug:
    msg: "{{ microk_status }}"

# Debug
# - name: grab kubectl verification message
#   shell: kubectl cluster-info dump
#   register: verification_msg

# - name: print verification message output
#   debug:
#     msg: "{{ verification_msg }}"