---

- name: Install Kubernetes
  snap:
    name: kubectl
    classic: true
    state: present
  become_user: root

- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: "/home/{{username}}"

- name: Install minikube
  shell: install minikube-linux-amd64 /usr/local/bin/minikube
  become_user: root